### ISSUE TITLE
Branch usage in Docker

### ISSUE THREAD

**Issue by nitishgupta** [CogComp/wikidump-preprocessing#3]
I just noticed that @HeglerTissot missed this usage of feature/sumodule branch in Dockerfile (i changed to master right now)
https://github.com/CogComp/wikidump-preprocessing/blob/master/Dockerfile#L13

@xrhan instead of making branches to contribute to the code, can you fork the repository and work on your fork's master and send pull requests?

For the branch that is open right now, I would suggest manually copy the changes (there aren't many) and send a pull request from that fork.

**Comment by xrhan** [comment]
Hi Nitish, could you check if we can merge the current dev branch? I have made all the required changes we have discussed before (those listed in the bullet points).

**Comment by nitishgupta** [comment]
Hi Nicole, there seems to be some confusion regarding the correct usage of makefile and Docker. Hegler had made a comment on the pull request and I had asked to meet in person on Monday. Would you have some time to come to the office on Monday?

**Comment by xrhan** [comment]
I am available on Monday from 11am-12pm and 3-4:30pm.
Yes, I saw the comment. I think maybe I can change the docker file to have COPY so we can reach a consensus.
Other than the COPY/git clone part, is there anything else that we need to discuss more on?

**Comment by nitishgupta** [comment]
How about 11am on Monday? You can come to my office (same as Shyam's 456C, 3401 Walnut).
Don't make any more changes now until we discuss.
